### ISSUE TITLE
Crash while generating map for multiple 3 position

### ISSUE THREAD

**Issue by andkamashev** [FAForever/Neroxis-Map-Generator#318]
Here are logs.
It seems always reproducable for 3 players  and 3 teams and sometimes for 6.
Starting pipeline
java.util.concurrent.CompletionException: java.lang.reflect.InvocationTargetException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.faforever.neroxis.mask.Mask.copy(Mask.java:890)
	at com.faforever.neroxis.mask.Mask.copy(Mask.java:877)
	at com.faforever.neroxis.mask.Mask.getFinalMask(Mask.java:882)
	at com.faforever.neroxis.generator.texture.TextureGenerator.lambda$generatePreview$2(TextureGenerator.java:79)
	at com.faforever.neroxis.util.DebugUtil.timedRun(DebugUtil.java:68)
	at com.faforever.neroxis.generator.texture.TextureGenerator.generatePreview(TextureGenerator.java:76)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 6 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.faforever.neroxis.util.vector.Vector.copy()" because "value" is null
	at com.faforever.neroxis.mask.VectorMask.set(VectorMask.java:147)
	at com.faforever.neroxis.mask.VectorMask.fill(VectorMask.java:211)
	at com.faforever.neroxis.mask.VectorMask.lambda$copyFrom$7(VectorMask.java:96)
	at com.faforever.neroxis.mask.Mask.enqueue(Mask.java:230)
	at com.faforever.neroxis.mask.VectorMask.copyFrom(VectorMask.java:96)
	at com.faforever.neroxis.mask.VectorMask.copyFrom(VectorMask.java:22)
	at com.faforever.neroxis.mask.Mask.init(Mask.java:82)
	at com.faforever.neroxis.mask.Mask.<init>(Mask.java:51)
	at com.faforever.neroxis.mask.OperationsMask.<init>(OperationsMask.java:16)
	at com.faforever.neroxis.mask.VectorMask.<init>(VectorMask.java:59)
	at com.faforever.neroxis.mask.Vector4Mask.<init>(Vector4Mask.java:43)
	... 18 more

**Comment by Sheikah45** [comment]
Cannot reproduce anymore
