### ISSUE TITLE
Terrain Symmetry set to NONE leads to Error

### ISSUE THREAD

**Issue by MarcusOnGit** [FAForever/Neroxis-Map-Generator#385]
Hi there,
i just found out by fiddling around with the options that --terrain-symmetry=NONE does not work becuase it leads to an error.
```
java -jar .\NeroxisGen_1.11.0.jar --terrain-symmetry=NONE
neroxis_map_generator_1.11.0_zgzeu2fmp2ajs_ayeaea34b5yxypczcu
java.lang.IllegalArgumentException: bound must be positive
        at java.base/java.util.Random.nextInt(Random.java:557)
        at com.faforever.neroxis.util.SymmetrySelector.getSymmetrySettingsFromTerrainSymmetry(SymmetrySelector.java:46)
        at com.faforever.neroxis.generator.style.StyleGenerator.initialize(StyleGenerator.java:125)
        at com.faforever.neroxis.generator.style.StyleGenerator.generate(StyleGenerator.java:95)
        at com.faforever.neroxis.generator.MapGenerator.generate(MapGenerator.java:485)
        at com.faforever.neroxis.generator.MapGenerator.call(MapGenerator.java:140)
        at com.faforever.neroxis.generator.MapGenerator.call(MapGenerator.java:56)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at com.faforever.neroxis.generator.MapGenerator.lambda$main$0(MapGenerator.java:98)
        at com.faforever.neroxis.util.DebugUtil.timedRun(DebugUtil.java:68)
        at com.faforever.neroxis.util.DebugUtil.timedRun(DebugUtil.java:42)
        at com.faforever.neroxis.generator.MapGenerator.main(MapGenerator.java:90)
```

**Comment by Sheikah45** [comment]
No longer occurs
